language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
    - compiler: clang
      os: osx

script:
  - mkdir build && cd build
  - cmake ../ -DBFIO_EXAMPLES=ON -DBFIO_TESTS=ON
  - make all
  - make test

branches:
  only:
    - master

notifications:
  email: false
